/** Local assets in /public/Images — aligned with design mockups. */
export const beachImages = {
  hero: "/Images/image9.jpg",
  vibesSection: "/Images/image13.png",
  globalSection: "/Images/image5.png",
  mapPanel: "/Images/image4.png",
  browseAllMoods: "/Images/image25.jpg",
  moods: {
    party: "/Images/image8.png",
    surf: "/Images/image11.png",
    hidden: "/Images/image14.png",
    family: "/Images/image6.png",
    lgbtq: "/Images/image16.png",
    bikini: "/Images/image10.png",
  },
  trending: {
    diamond: "/Images/image20.png",
    fulhadhoo: "/Images/image22.png",
    conigli: "/Images/image5.png",
    whitehaven: "/Images/image13.png",
  },
  /** Extra homepage sections */
  home: {
    nyRockaway: "/Images/image20.png",
    nyJacob: "/Images/image22.png",
    nyFort: "/Images/image7.png",
    nySouth: "/Images/image9.jpg",
    nyMidland: "/Images/image14.png",
    hiddenHero: "/Images/image17.png",
    hiddenPalawan: "/Images/image14.png",
    hiddenBarril: "/Images/image23.png",
    leavesLeft: "/Images/leavesleft.svg",
    leavesRight: "/Images/leavesright.svg",
    snorkel: "/Images/imge1.png",
    sailMed: "/Images/image15.png",
    aegeanJump: "/Images/image2.jpg",
    pacificSunset: "/Images/things-to-do.jpg",
    surfEvent: "/Images/beachevents.png",
    journalHero: "/Images/jurnal1.png",
    journalThumb1: "/Images/journal2.png",
    journalThumb2: "/Images/journal3.png",
    journalThumb3: "/Images/journal4.png",
    planTripBg: "/Images/image6.png",
    footerWave: "/Images/image30.png",
    stay1: "/Images/nearbeaches1.jpg",
    stay2: "/Images/nearbeaches2.jpg",
    stay3: "/Images/nearbeaches3.jpg",
    stay4: "/Images/nearbeaches4.jpg",
    stay5: "/Images/nearbeaches5.jpg",
  },
  explore: {
    beach1: "/Images/exp1.png",
    beach2: "/Images/exp2.png",
    beach3: "/Images/exp3.png",
    beach4: "/Images/exp4.png",
    weather: "/Images/weather.png",
  },
} as const;
